In [139]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import warnings
warnings.filterwarnings('ignore') # supress the warnings

# Production Drivers

In [170]:
milk_production= pd.read_csv("milk_production.csv")
milk_production.head()

,DATAFLOW,LAST UPDATE,freq,dairyprod,milkitem,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,Farm milk products delivered to dairies,Products obtained (1 000 t),Albania,2015,NaN,NaN,NaN
1,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,Farm milk products delivered to dairies,Products obtained (1 000 t),Albania,2016,NaN,NaN,NaN
2,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,Farm milk products delivered to dairies,Products obtained (1 000 t),Albania,2017,NaN,NaN,NaN
3,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,Farm milk products delivered to dairies,Products obtained (1 000 t),Albania,2018,NaN,NaN,NaN
4,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,Farm milk products delivered to dairies,Products obtained (1 000 t),Albania,2019,NaN,NaN,NaN

In [171]:
milk_production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6600 entries, 0 to 6599
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATAFLOW     6600 non-null   object
 1   LAST UPDATE  6600 non-null   object
 2   freq         6600 non-null   object
 3   dairyprod    6600 non-null   object
 4   milkitem     6600 non-null   object
 5   geo          6600 non-null   object
 6   TIME_PERIOD  6600 non-null   int64
 7   OBS_VALUE    1913 non-null   float64
 8   OBS_FLAG     182 non-null    object
 9   CONF_STATUS  26 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 515.8+ KB

In [172]:
milk_production['geo'].unique()

array(['Albania', 'Austria', 'Belgium', 'Bulgaria', 'Switzerland',
       'Cyprus', 'Czechia', 'Germany',
       'Federal Republic of Germany (former territory of the FRG only)',
       'Denmark', 'Estonia', 'Greece', 'Spain',
       'European Community - 10 countries (1981-1985)',
       'European Community - 12 countries (1986-1994)',
       'European Union - 25 countries (2004-2006)',
       'European Union - 27 countries (from 2020)',
       'European Union - 28 countries (2013-2020)',
       'European Community - 9 countries (1973-1980)', 'Finland',
       'France', 'Croatia', 'Hungary', 'Ireland', 'Iceland', 'Italy',
       'Lithuania', 'Luxembourg', 'Latvia', 'Montenegro',
       'North Macedonia', 'Malta', 'Netherlands', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Serbia', 'Sweden', 'Slovenia', 'Slovakia',
       'Türkiye', 'United Kingdom', 'Kosovo*'], dtype=object)

In [174]:
milk_production["dairyprod"].unique()

array(['Farm milk products delivered to dairies',
       'Milk products, other than drinking milk, cream, butter and cheese, delivered to dairies',
       'Milk products, other than milk and cream, delivered to dairies',
       'Raw milk, total available on farms',
       'Raw milk delivered to dairies'], dtype=object)

In [176]:
milk_production["milkitem"].unique()

array(['Products obtained (1 000 t)',
       'Utilization of skimmed milk and buttermilk (1 000 t)',
       'Utilization of whole milk (1 000 t)'], dtype=object)

In [160]:
# Filter the dataframe to contain only Ireland data
milk_production_ie = milk_production[(milk_production["geo"] == "Ireland") & (milk_production["dairyprod"]== "Raw milk, total available on farms") & 
    (milk_production["milkitem"]== "Products obtained (1 000 t)")]
milk_production_ie.head()

,DATAFLOW,LAST UPDATE,freq,dairyprod,milkitem,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
4190,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,2015,6604.41,NaN,NaN
4191,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,2016,6871.94,NaN,NaN
4192,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,2017,7498.94,NaN,NaN
4193,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,2018,7831.25,NaN,NaN
4194,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,2019,8244.87,NaN,NaN

In [164]:
milk_production_ie.shape

(10, 10)

In [166]:
milk_production_ie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 4190 to 4199
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATAFLOW     10 non-null     object
 1   LAST UPDATE  10 non-null     object
 2   freq         10 non-null     object
 3   dairyprod    10 non-null     object
 4   milkitem     10 non-null     object
 5   geo          10 non-null     object
 6   TIME_PERIOD  10 non-null     int64
 7   OBS_VALUE    10 non-null     float64
 8   OBS_FLAG     0 non-null      object
 9   CONF_STATUS  0 non-null      object
dtypes: float64(1), int64(1), object(8)
memory usage: 880.0+ bytes

In [167]:
milk_production_ie.describe(include='object')

,DATAFLOW,LAST UPDATE,freq,dairyprod,milkitem,geo,OBS_FLAG,CONF_STATUS
count,10,10,10,10,10,10,0,0
unique,1,1,1,1,1,1,0,0
top,ESTAT:APRO_MK_FARM$DEFAULTVIEW(1.0),04/12/25 11:00:00,Annual,"Raw milk, total available on farms",Products obtained (1 000 t),Ireland,NaN,NaN
freq,10,10,10,10,10,10,NaN,NaN

Dropping the irrelevant features based on dataset knowledge and previous outputs.

In [168]:
milk_production_ie = milk_production_ie.drop(['DATAFLOW','LAST UPDATE','freq','dairyprod','milkitem','geo',
     'OBS_FLAG','CONF_STATUS'], axis=1).reset_index(drop=True)

milk_production_ie.head()

   TIME_PERIOD  OBS_VALUE
0         2015    6604.41
1         2016    6871.94
2         2017    7498.94
3         2018    7831.25
4         2019    8244.87

In [169]:
milk_production_ie = milk_production_ie.rename(columns={'TIME_PERIOD': 'year', 'OBS_VALUE':'milk_production (1000 t)'})
milk_production_ie.head()

   year  milk_production (1000 t)
0  2015                   6604.41
1  2016                   6871.94
2  2017                   7498.94
3  2018                   7831.25
4  2019                   8244.87

In [81]:
milk_delivered = pd.read_csv("milk_delivered_by_farmers.csv")

In [82]:
milk_delivered.head()

,Statistic Label,Year,Domestic or Import Source,UNIT,VALUE
0,Intake of Cows Milk by Milk Processors and Co-Ops,1992,Domestic,Million Litres,5105.9
1,Intake of Cows Milk by Milk Processors and Co-Ops,1993,Domestic,Million Litres,5052.1
2,Intake of Cows Milk by Milk Processors and Co-Ops,1994,Domestic,Million Litres,5119.5
3,Intake of Cows Milk by Milk Processors and Co-Ops,1995,Domestic,Million Litres,5135.9
4,Intake of Cows Milk by Milk Processors and Co-Ops,1996,Domestic,Million Litres,5144.3

In [83]:
milk_delivered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Statistic Label            34 non-null     object
 1   Year                       34 non-null     int64
 2   Domestic or Import Source  34 non-null     object
 3   UNIT                       34 non-null     object
 4   VALUE                      34 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.5+ KB

In [84]:
milk_delivered.describe(include='object')

,Statistic Label,Domestic or Import Source,UNIT
count,34,34,34
unique,1,1,1
top,Intake of Cows Milk by Milk Processors and Co-Ops,Domestic,Million Litres
freq,34,34,34

In [85]:
# Filter the dataframe to contain only relevant features
milk_delivered = milk_delivered[(milk_delivered["Domestic or Import Source"] == "Domestic")][['Year','VALUE']]
milk_delivered = milk_delivered.rename(columns={'Year':'year','VALUE':'milk_delivered (million_litres)'})
milk_delivered.head()

   year  milk_delivered (million_litres)
0  1992                           5105.9
1  1993                           5052.1
2  1994                           5119.5
3  1995                           5135.9
4  1996                           5144.3

In [86]:
milk_delivered.shape

(34, 2)

In [87]:
dairy_cows_stock = pd.read_csv("dairy_cow_stock.csv")

In [88]:
dairy_cows_stock.head()

            STATISTIC Label  Year Type of Animal      UNIT   VALUE
0  Farm Animals in December  2005     Dairy cows  Thousand   995.8
1  Farm Animals in December  2006     Dairy cows  Thousand  1022.8
2  Farm Animals in December  2007     Dairy cows  Thousand  1017.3
3  Farm Animals in December  2008     Dairy cows  Thousand  1024.1
4  Farm Animals in December  2009     Dairy cows  Thousand  1022.4

In [89]:
dairy_cows_stock.shape

(20, 5)

In [90]:
dairy_cows_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATISTIC Label  20 non-null     object
 1   Year             20 non-null     int64
 2   Type of Animal   20 non-null     object
 3   UNIT             20 non-null     object
 4   VALUE            20 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 932.0+ bytes

In [91]:
dairy_cows_stock.describe(include="object")

                 STATISTIC Label Type of Animal      UNIT
count                         20             20        20
unique                         1              1         1
top     Farm Animals in December     Dairy cows  Thousand
freq                          20             20        20

In [92]:
# Filter the dataframe to contain only relevant features
dairy_cows_stock = dairy_cows_stock[['Year','VALUE']]
dairy_cows_stock = dairy_cows_stock.rename(columns={'Year':'year','VALUE':' dairy_cows (thousand)'})
dairy_cows_stock.head()

   year   dairy_cows (thousand)
0  2005                   995.8
1  2006                  1022.8
2  2007                  1017.3
3  2008                  1024.1
4  2009                  1022.4

In [93]:
processed_dairy = pd.read_csv("processed_dairy_production.csv")
processed_dairy.head()

                STATISTIC Label  Year              Product        UNIT  VALUE
0  Production of Dairy Products  1992               Cheese  000 Tonnes   93.5
1  Production of Dairy Products  1992               Butter  000 Tonnes  115.7
2  Production of Dairy Products  1992  Skimmed Milk Powder  000 Tonnes   97.0
3  Production of Dairy Products  1993               Cheese  000 Tonnes   92.7
4  Production of Dairy Products  1993               Butter  000 Tonnes  111.7

In [94]:
processed_dairy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATISTIC Label  102 non-null    object
 1   Year             102 non-null    int64
 2   Product          102 non-null    object
 3   UNIT             102 non-null    object
 4   VALUE            101 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.1+ KB

In [95]:
processed_dairy.describe(include="object")

                     STATISTIC Label Product        UNIT
count                            102     102         102
unique                             1       3           1
top     Production of Dairy Products  Cheese  000 Tonnes
freq                             102      34         102

In [96]:
processed_dairy["Product"].unique()

array(['Cheese', 'Butter', 'Skimmed Milk Powder'], dtype=object)

In [97]:
# Converting long format to wide format using "pivot"
processed_dairy = processed_dairy.pivot(index="Year",values="VALUE",columns="Product").reset_index()
processed_dairy.columns.name = None  # Resetting column index name
processed_dairy=processed_dairy.rename(columns={"Year":"year","Butter":"butter_production (t)","Cheese":"cheese_production (t)",
                                                "Skimmed Milk Powder":"skimmed_milk_powder(t)"})
processed_dairy.head()

   year  butter_production (t)  cheese_production (t)  skimmed_milk_powder(t)
0  1992                  115.7                   93.5                    97.0
1  1993                  111.7                   92.7                   102.5
2  1994                  126.9                   92.7                   129.3
3  1995                  142.3                   79.9                   114.8
4  1996                  142.0                   97.0                   119.0

# Trade Drivers

In [98]:
trade_value = pd.read_csv("fao_trade_dataset.csv")
trade_value.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,TCL,Crops and livestock products,372,Ireland,5610,Import quantity,22241.01,Butter of cow milk,1961,1961,t,41.0,A,Official figure,NaN
1,TCL,Crops and livestock products,372,Ireland,5622,Import value,22241.01,Butter of cow milk,1961,1961,1000 USD,30.0,A,Official figure,NaN
2,TCL,Crops and livestock products,372,Ireland,5910,Export quantity,22241.01,Butter of cow milk,1961,1961,t,15399.0,A,Official figure,NaN
3,TCL,Crops and livestock products,372,Ireland,5922,Export value,22241.01,Butter of cow milk,1961,1961,1000 USD,10652.0,A,Official figure,NaN
4,TCL,Crops and livestock products,372,Ireland,5610,Import quantity,22241.01,Butter of cow milk,1962,1962,t,74.0,A,Official figure,NaN

In [99]:
trade_value.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       1280 non-null   object
 1   Domain            1280 non-null   object
 2   Area Code (M49)   1280 non-null   int64
 3   Area              1280 non-null   object
 4   Element Code      1280 non-null   int64
 5   Element           1280 non-null   object
 6   Item Code (CPC)   1280 non-null   float64
 7   Item              1280 non-null   object
 8   Year Code         1280 non-null   int64
 9   Year              1280 non-null   int64
 10  Unit              1280 non-null   object
 11  Value             1280 non-null   float64
 12  Flag              1280 non-null   object
 13  Flag Description  1280 non-null   object
 14  Note              9 non-null      object
dtypes: float64(2), int64(4), object(9)
memory usage: 150.1+ KB

In [64]:
trade_value.describe(include = "object")

,Domain Code,Domain,Area,Element,Item,Unit,Flag,Flag Description,Note
count,1280,1280,1280,1280,1280,1280,1280,1280,9
unique,1,1,1,4,5,2,2,2,1
top,TCL,Crops and livestock products,Ireland,Import quantity,Butter of cow milk,t,A,Official figure,Estimated data using trading partners database
freq,1280,1280,1280,320,256,640,1271,1271,9

In [101]:
trade_value["Item"].unique()

array(['Butter of cow milk', 'Cheese from whole cow milk',
       'Raw milk of cattle', 'Skim milk and whey powder',
       'Whole milk powder'], dtype=object)

In [102]:
trade_value[["Year","Item","Element"]]

      Year                Item          Element
0     1961  Butter of cow milk  Import quantity
1     1961  Butter of cow milk     Import value
2     1961  Butter of cow milk  Export quantity
3     1961  Butter of cow milk     Export value
4     1962  Butter of cow milk  Import quantity
...    ...                 ...              ...
1275  2023   Whole milk powder     Export value
1276  2024   Whole milk powder  Import quantity
1277  2024   Whole milk powder     Import value
1278  2024   Whole milk powder  Export quantity
1279  2024   Whole milk powder     Export value

[1280 rows x 3 columns]

In [68]:
# Converting long format to wide format using "pivot"
trade_value = trade_value.pivot(index="Year",values="Item",columns="Element").reset_index()
trade_value.columns.name = None  # Resetting column index name
#processed_dairy=processed_dairy.rename(columns={"Year":"year","Butter":"butter_production (t)","Cheese":"cheese_production (t)",
     #                                           "Skimmed Milk Powder":"skimmed_milk_powder(t)"})
trade_value

ValueError: Index contains duplicate entries, cannot reshape